builds:
-
  goos:
    - darwin
    - linux
    - windows
  env:
    - CGO_ENABLED=0
  main: ./buffalo/main.go
  binary: buffalo-no-sqlite
  # hooks:
  #   pre: packr
  #   post: packr clean

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
brew:
   name: "{{.ProjectName}}"
   install: |
     bin.install "{{.Binary}}"
   # test: |
   #   system "#{bin}/{{.Binary}} version"
